/// Flutter icons AcademeCustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AcademeCustomIcons
///      fonts:
///       - asset: fonts/AcademeCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AcademeCustomIcons {
  AcademeCustomIcons._();

  static const _kFontFam = 'AcademeCustomIcons';
  static const _kFontPkg = null;

  static const IconData subscriptions = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
